name: bitly-server pipeline GHCR

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/server

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: bitly_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U docker"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure Node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        id: install-dependencies
        working-directory: ./server
        run: |
          pnpm install

      - name: Run tests
        id: run-tests
        working-directory: ./server
        env:
          DATABASE_URL: postgresql://docker:docker@localhost:5432/bitly_test
          NODE_ENV: test
        run: |
          pnpm test

  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure Node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        id: install-dependencies
        working-directory: ./server
        run: |
          pnpm install

      - name: Set up Docker Buildx
        id: set-up-docker-buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        id: login-ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tag
        id: generate-tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and export image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test

      - name: Run Trivy scanner
        id: run-trivy-scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test"
          format: "table"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH,MEDIUM,LOW"

      - name: Build and push the image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.generate-tag.outputs.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
